[package]
name = "escaping-the-depths"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "^0.16", features = ["wayland"] }
rand = "^0.9"

[dev-dependencies]
cucumber = "^0.21"
futures = "^0.3"

[[test]]
name = "mvp"
harness = false
